- README.md
- client/client.go
- client/frontend.go
- client/go.mod
- client/go.sum
- server/frontend.go
- server/go.mod
- server/go.sum
adopted the spdk client and server frontned apis to use new opi-frontend apis
the bridge code keeps cache of various objects, this allows for key association and return information on other situations. I have kept the code to query from spdk server from the bridge, to be sure that backend system has all the relevant information as well
pls review @glimchb
> Opi api changes

- README.md
- client/go.mod
- client/go.sum
- server/frontend.go
- server/go.mod
- server/go.sum
> fix code after API changes

- scripts/poc.sh
- server/frontend.go
in testing we use nqn.2016-06.io.spdk:cnode1
with pre-defined transport and listener
so need to keep this code for now
will remove once we add transport and listener calls
tracking this here #31 
> temp workaround for listener

- docker-compose.yml
- spdk/Dockerfile
For some reason when adding --with-vfio-user
RPM build is not working any more
So adding ugly hack `LDFLAGS=" "`
and `--without-shared`
> spdk: add vfio-user

- .golangci.yml
- server/frontend.go
- server/frontend_test.go
- server/server.go
> tests: implement FrontEnd NVMe

- client/Dockerfile
- docker-compose.yml
- server/Dockerfile
By introducing multi-stage build
And switching to alpine
And using grpcurl from docker
x10 size reduction !
```
$ docker images | grep opi
opi-storage-server                      main           44996bc55718   About a minute ago   50.7MB
ghcr.io/opiproject/opi-storage-server   main           ae1f6b66da01   18 hours ago         618MB
```
> docker: reduce images size

- server/backend_test.go
- server/frontend_test.go
- server/middleend_test.go
> Test refactor

- pkg/client/frontend.go
> Add missing parameters to SPDK client

- docker-compose.yml
- pkg/server/middleend.go
`Key2` is marked as optional but SPDK mandates it in the code still...
https://spdk.io/doc/jsonrpc.html#rpc_accel_crypto_key_create
```
spdk_1             | [2023-02-09 15:52:03.456606] accel_sw.c: 707:sw_accel_create_aes_xts: *ERROR*: key size 16 is not equal to key2 size 0 or is 0
```
Signed-off-by: Boris Glimcher <36732377+glimchb@users.noreply.github.com>
> Fixed #140 accel_crypto_key_create missing Key2

- pkg/client/middleend.go
- pkg/server/middleend.go
- pkg/server/middleend_test.go
> spdk: use pb.EncryptionType instead of hard-coded

- pkg/server/middleend.go
- pkg/server/spdk.go
> spdk: middle: add AccelCryptoKeyDestroy

- .github/workflows/docker-publish.yml
- ci: split spdk to a separate job, no matrix
- Publish spdk bridge to dockerhub as well
- rename opi-storage-server docker to a repo name
> Publish spdk bridge to dockerhub as well

- Dockerfile
- cmd/main.go
- pkg/backend/backend.go
- pkg/backend/backend_test.go
- pkg/frontend/frontend.go
- pkg/frontend/frontend_test.go
- pkg/middleend/middleend.go
- pkg/middleend/middleend_test.go
- pkg/server/jsonrpc.go
- pkg/server/server.go
- pkg/server/spdk.go
- pkg/server/spdk_test.go
split to several packages:
- frontend
- middleend
- backend
This will help importing this library from other projects
TODOs:
- remove some code dup in tests
- split to more files like nvme vs virtio
> Folder restructure

- cmd/main.go
- pkg/frontend/frontend.go
- pkg/frontend/frontend_test.go
- pkg/frontend/nvme.go
- pkg/frontend/nvme_test.go
In this change, NVMe related global variables are moved into frontend Server structure. It is good design practise to avoid global variables in the code. It makes design flexible and testable. NVMe parameters are made exported from package to provide possibility for clients to leverage them in xPU specific code.
In addition, this patch removes dependency on test execution order.
> Avoid using global variables for NVMe parameters.

- cmd/main.go
- pkg/backend/aio.go
- pkg/backend/backend.go
- pkg/backend/backend_test.go
- pkg/backend/nvme.go
- pkg/backend/nvme_test.go
- pkg/frontend/frontend.go
- pkg/frontend/frontend_test.go
- pkg/frontend/nvme.go
- pkg/frontend/nvme_test.go
- pkg/frontend/scsi.go
- pkg/middleend/middleend.go
- pkg/middleend/middleend_test.go
- pkg/server/jsonrpc.go
- pkg/server/utils.go
In this change JSON RPC related global variables were moved into a dedicated structure. It makes design flexible and testable. In addition tests are reworked to create a new JSON RPC structure per test. It makes the tests hermetic and allows to run them in parallel.
Patch provides backward compatibility for other bridges til they reworked to use JSONRPC interface injection
> Avoid using globals for JSON RPC.

- cmd/main.go
- pkg/kvm/kvm.go
- pkg/kvm/monitor.go
In this PR communication with a QEMU instance is automated to plug/unplug SPDK virtio-blk devices on CreateVirtioBlk/DeleteVirtioBlk
> Add virtio-blk to KVM server

- pkg/backend/aio.go
- pkg/backend/aio_test.go
- pkg/backend/null.go
- pkg/backend/null_test.go
- pkg/backend/nvme.go
- pkg/frontend/blk.go
- pkg/frontend/nvme.go
- pkg/frontend/scsi.go
- pkg/frontend/scsi_test.go
- pkg/kvm/kvm_test.go
- pkg/middleend/middleend.go
- pkg/server/jsonrpc_test.go
Due to golangci update to 1.52.0 version where unused arguments are checked, all unused variables should be replaced with `_` to pass the check
> Use underscore for unused arguments.

- cmd/main.go
- docker-compose.yml
- pkg/frontend/frontend.go
- pkg/frontend/nvme.go
- pkg/frontend/nvme_test.go
net.LookupIP takes time to get resolved, which slows down frontend test execution. Instead, a stub call which returns a predefined value can be used to get a quicker feedback from the tests.
> TCP transport uses provided IPv4 address to listen on

- pkg/middleend/middleend.go
- pkg/middleend/middleend_test.go
When encrypted volume is created, a crypto key and then a crypto bdev are created. Delete procedure destroyed a crypto bdev, but missed a key deletion. This prevented a new encrypted volume creation.
Take error codes and messages from UpdateEncryptedVolume.
> Destroy crypto key on DeleteEncryptedVolume.

- go.mod
- go.sum
- pkg/backend/aio.go
- pkg/backend/aio_test.go
- pkg/backend/backend.go
- pkg/backend/null.go
- pkg/backend/null_test.go
- pkg/backend/nvme.go
- pkg/backend/nvme_test.go
- pkg/frontend/blk.go
- pkg/frontend/blk_test.go
- pkg/frontend/frontend.go
- pkg/frontend/nvme.go
- pkg/frontend/nvme_test.go
- pkg/frontend/scsi.go
- pkg/middleend/middleend.go
- pkg/middleend/middleend_test.go
- pkg/server/utils.go
see https://google.aip.dev/132 and https://google.aip.dev/158
If API returned partial result:
- generate new NextPageToken based on UUID
- return the token in the response
- save the token to re-use later on
- Empty NextPageToken indicates end of results list
If non empty token received in API request:
- received token, find it in local DB and retrieve offset
- return results starting from offset
Token expiration is not implemeted yet.
> List: add pagination support

- pkg/backend/aio.go
- pkg/backend/null.go
- pkg/backend/nvme.go
- pkg/frontend/blk.go
- pkg/frontend/nvme.go
- pkg/frontend/scsi.go
see https://google.aip.dev/133#user-specified-ids
this commit is preparation to handle `{resource}_id` properly
> create: log {resource}_id field if provided by user

- docker-compose.yml
- pkg/backend/aio.go
- pkg/backend/aio_test.go
- pkg/backend/null.go
- pkg/backend/null_test.go
- pkg/backend/nvme.go
- pkg/backend/nvme_test.go
- pkg/frontend/blk.go
- pkg/frontend/blk_test.go
- pkg/frontend/nvme.go
- pkg/frontend/nvme_test.go
- pkg/frontend/scsi.go
- pkg/kvm/blk_test.go
- pkg/kvm/nvme_test.go
- pkg/middleend/encryption_test.go
- pkg/middleend/qos_test.go
- scripts/tests.sh
using this algorithm (discussed in slack):
```
if request.book_id != ""
request.book.name = "//api.opiproject.org/books/{request.book_id}"
else
request.book.name = "//api.opiproject.org/books/{generate_new_random_uuid}"
db[request.book.name] = request
return request.book
```
> create: use {resource}_id field if provided by user

- pkg/backend/aio_test.go
- pkg/backend/null_test.go
- pkg/backend/nvme_test.go
- pkg/frontend/blk_test.go
- pkg/frontend/nvme_test.go
- pkg/kvm/blk_test.go
- pkg/kvm/nvme_test.go
id/name/handle field is filled by the server instead
one can specify {resource}_id field instead
> tests: do not send id/name/handle value on the create request

- pkg/backend/aio.go
- pkg/backend/aio_test.go
- pkg/backend/null.go
- pkg/backend/null_test.go
- pkg/backend/nvme.go
- pkg/backend/nvme_test.go
- pkg/frontend/blk.go
- pkg/frontend/blk_test.go
- pkg/frontend/nvme.go
- pkg/frontend/nvme_test.go
- pkg/frontend/scsi.go
- pkg/kvm/blk_test.go
previous PR sent empty value, now remove the entire object
id/name/handle field is filled by the server instead
one can specify {resource}_id field instead
> tests: do not send id/name/handle OBJECT on the create request

- pkg/kvm/blk.go
- pkg/kvm/kvm.go
- pkg/kvm/kvm_test.go
- pkg/kvm/nvme.go
- pkg/kvm/nvme_test.go
opi-spdk-bridge can generate NVMe controller id if it is not provided and build controller name. Those names can add some issues for KVM related code:
For NVMe ad virtio-blk:
* QMP requires object ids start from a letter. An SPDK bridge uses uuid if an id is not specified. Add toQemuID function to add prefixes to QEMU related ids which are based on controller names.
For NVMe controller only:
* NVMe controller directory should exist before an SPDK request to create that controller is sent. NVMe controller id/name cannot be used as directory name since it is not a mandatory field. Use subsystem id instead, since it must exist before a controller is created.
After this PR, https://github.com/opiproject/opi-spdk-bridge/pull/335 can be rebased and merged
> Adjust KVM create calls to use properly generated names

- cmd/main.go
- pkg/kvm/blk.go
- pkg/kvm/blk_test.go
- pkg/kvm/kvm.go
- pkg/kvm/kvm_test.go
- pkg/kvm/location.go
- pkg/kvm/location_test.go
- pkg/kvm/monitor.go
- pkg/kvm/nvme.go
- pkg/kvm/nvme_test.go
QEMU QMP provides an ability to assign devices on a specific bus with a specific address. This can be useful if we need an ability to identify a created device within a running VM
> Add ability for KVM to assign devices on specific buses.

- pkg/frontend/nvme.go
> nvme: check input parameters validity

- pkg/backend/aio.go
- pkg/backend/null.go
- pkg/frontend/blk.go
- pkg/frontend/nvme.go
- pkg/frontend/scsi.go
- pkg/middleend/encryption.go
Fixes #417
According to AIP-122 a resource name includes a resource ID.
That part which is extracted by path.Base is probably resource ID, not name
> rename: resourceId is a better name

- pkg/backend/aio_test.go
- pkg/backend/null_test.go
- pkg/backend/nvme_controller_test.go
- pkg/backend/nvme_path_test.go
- pkg/frontend/blk_test.go
- pkg/frontend/nvme_controller_test.go
- pkg/frontend/nvme_namespace_test.go
- pkg/frontend/nvme_subsystem_test.go
- pkg/middleend/encryption_test.go
> tests: add malformed name to Get tests

- pkg/middleend/encryption_test.go
- pkg/middleend/qos_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/501
> Uniformly check returned error on OK response in middleend

- pkg/kvm/blk_test.go
- pkg/kvm/kvm_test.go
- pkg/kvm/nvme_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/501
> Uniformly check returned error on OK response in kvm

- pkg/backend/aio_test.go
- pkg/backend/null_test.go
- pkg/backend/nvme_controller_test.go
- pkg/backend/nvme_path_test.go
- pkg/server/utils.go
- pkg/server/utils_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/533
> Uniformly check nil responses in backend tests

- docker-compose.yml
- scripts/tests.sh
> tests: e2e: add CreateNvmeRemoteController and CreateNvmePath

- .github/workflows/docker-publish.yml
fix https://github.com/opiproject/opi-spdk-bridge/issues/576
> ci: keep opi-api version in built image's label

- pkg/server/tls.go
- pkg/server/tls_test.go
copy from https://github.com/opiproject/opi-intel-bridge/tree/main/pkg/utils
> feat: add TLS utils to be used by main for gRPC connection

- cmd/main.go
> feat: add TLS option for gRPC connection

- pkg/backend/aio.go
- pkg/backend/aio_validate.go
- pkg/backend/null.go
- pkg/backend/null_validate.go
- pkg/backend/nvme_controller.go
- pkg/backend/nvme_controller_validate.go
- pkg/backend/nvme_path.go
- pkg/backend/nvme_path_validate.go
- pkg/frontend/blk.go
- pkg/frontend/blk_validate.go
- pkg/frontend/nvme_controller.go
- pkg/frontend/nvme_controller_validate.go
- pkg/frontend/nvme_namespace.go
- pkg/frontend/nvme_namespace_validate.go
- pkg/frontend/nvme_subsystem.go
- pkg/frontend/nvme_subsystem_test.go
- pkg/frontend/nvme_subsystem_validate.go
- pkg/frontend/scsi_validate.go
- pkg/middleend/encryption.go
- pkg/middleend/encryption_validate.go
- pkg/middleend/qos.go
- pkg/middleend/qos_validate.go
- refactor(frontend): split validate logic to a new file
- refactor(backend): split validate logic to a new file
- refactor(middleend): split validate logic to a new file
- test(nvme): check nqn, model and serial
- fix(backend): add missing UpdateNvmeRemoteController
> refactor: split validate logic to a new file

- cmd/main.go
- go.mod
- go.sum
- pkg/backend/aio.go
- pkg/backend/null.go
- pkg/backend/nvme_controller.go
- pkg/backend/nvme_path.go
- pkg/frontend/blk.go
- pkg/frontend/nvme_controller.go
- pkg/frontend/nvme_namespace.go
- pkg/frontend/nvme_subsystem.go
- pkg/frontend/scsi.go
- pkg/middleend/encryption.go
- pkg/middleend/qos.go
- pkg/utils/interceptors.go
Use https://github.com/grpc-ecosystem/go-grpc-middleware `logging` package to log requests/responses/errors.
With the current events for logging, logs for a call look like
```
2023/09/28 12:52:32 [msg INFO :started call protocol grpc grpc.component server grpc.service opi_api.storage.v1.NvmeRemoteControllerService grpc.method DeleteNvmeRemoteController grpc.method_type unary peer.address 127.0.0.1:38508 grpc.start_time 2023-09-28T12:52:32+02:00 grpc.time_ms 0.022]
2023/09/28 12:52:32 [msg INFO :request received protocol grpc grpc.component server grpc.service opi_api.storage.v1.NvmeRemoteControllerService grpc.method DeleteNvmeRemoteController grpc.method_type unary peer.address 127.0.0.1:38508 grpc.start_time 2023-09-28T12:52:32+02:00 grpc.recv.duration 22.551µs grpc.request.content …
```
> feat: move gRPC call request/reponse/error logging into interceptor

- pkg/backend/nvme_path.go
Fixes #677
because in compose we map /var/tmp and not /tmp folder
> fix(psk): change PSK temp key file location

- docker-compose.yml
- pkg/frontend/nvme_subsystem.go
- pkg/frontend/transport.go
- scripts/tests.sh
> ci: add support for Nvme/TLS connection

- pkg/kvm/transport.go
- pkg/kvm/transport_test.go
fix https://github.com/opiproject/opi-spdk-bridge/issues/700
> fix(kvm): do not allow vfiouser controller for subsys with hostnqn

- cmd/main.go
- go.mod
- go.sum
- pkg/backend/aio.go
- pkg/backend/null.go
- pkg/backend/nvme_path.go
- pkg/frontend/blk.go
- pkg/frontend/frontend_test.go
- pkg/frontend/nvme_controller.go
- pkg/frontend/nvme_namespace.go
- pkg/frontend/nvme_subsystem.go
- pkg/frontend/scsi.go
- pkg/kvm/kvm_test.go
- pkg/middleend/encryption.go
- pkg/middleend/qos.go
- pkg/middleend/qos_test.go
- pkg/utils/server.go
> fix: rename SpdkJSONRPC to Client

- README.md
- docker-compose.yml
- pkg/frontend/nvme_controller_test.go
- pkg/utils/resource.go
- scripts/tests.sh
The full resource names are changed to resource names due to the following reasons:
1. HTTP gateway sends resource names in that form
2. Based on explanations from this patch: https://github.com/aip-dev/google.aip.dev/commit/00e3ac744fb975ae046910dbfd57136e01d86059
3. [Aip-122](https://google.aip.dev/122) also mentions: Resources must expose a name field that contains its resource name. (they differentiate between resource name and full resource name)
As I understand, a full resource names are used when a field refers to resources in multiple APIs and ambiguity can arise. For example, if a field can refer to a book in a library API, a product in an e-commerce API, or a user in an authentication API, just using the relative resource name could lead to confusion. In this case, the field …
> fix: full resource names to resource names in names

- README.md
- docker-compose.yml
- pkg/frontend/nvme_controller_test.go
- pkg/utils/resource.go
- scripts/tests.sh
the used parent collection names are not consistent with ones described in [API](https://github.com/opiproject/opi-api/blob/main/storage/frontend_nvme.proto)
CI requires https://github.com/opiproject/godpu/pull/438 to pass
Unblocks HTTP frontend https://github.com/opiproject/opi-spdk-bridge/pull/878
> fix(frontend): precede nvme parent collections with nvme
