opiproject/opi-spdk-bridge

client/Dockerfile, server/Dockerfile
=> tests: call go test

server/frontend.go
=> frontend: add nsid to NVMeNamespaceList

README.md
=> update readme with fixed params

client/frontend.go, client/go.mod, client/go.sum, server/frontend.go, server/go.mod, server/go.sum
=> fix code after API changes

README.md
=> update readme with new API examples

.github/workflows/go.yml
=> CI: add go

server/backend.go
=> add UUID to NullDebug reply

client/backend.go, client/frontend.go, client/go.mod, client/go.sum, server/backend.go, server/frontend.go, server/go.mod, server/go.sum, server/server.go
=> fix renaming

README.md, client/middleend.go, server/middleend.go, server/server.go, server/spdk.go, spdk/Dockerfile
implementing new APIs defined at https://github.com/opiproject/opi-api/pull/208
=> Add crypto device example

.github/workflows/poc-storage.yml, docker-compose.yml, scripts/poc.sh
=> CI: simplify build by adding spdk to the matrix

scripts/poc.sh, server/frontend.go, server/spdk.go
=> Add CreateNVMeController and DeleteNVMeController

scripts/poc.sh, server/frontend.go
=> Allow real IP instead of lo

.github/workflows/poc-storage.yml
=> rename ci job

README.md, docker-compose.yml, scripts/poc.sh
=> spdk: disable allow_any_host

README.md, client/backend.go, server/backend.go
=> BE: fill more data to the remote nvme ctrl

server/frontend_test.go, server/middleend.go, server/middleend_test.go
=> tests: implement MiddleEnd crypto

server/backend.go, server/backend_test.go, server/frontend_test.go
=> tests: implement BackEnd nvmf

pkg/client/frontend.go
=> Add missing parameters to SPDK client

cmd/client/client.go, pkg/client/frontend.go
=> add prints

pkg/client/frontend.go, pkg/server/frontend.go, pkg/server/frontend_test.go
=> UpdateNVMeSubsystem: Unimplemented

pkg/client/backend.go, pkg/client/frontend.go, pkg/client/middleend.go
=> client: remove codedup

cmd/client/client.go, pkg/client/backend.go, pkg/client/frontend.go, pkg/client/middleend.go
=> client: propagate error codes

.github/workflows/docker-publish.yml, .github/workflows/release.yaml
=> ci: add release

.github/workflows/go.yml
=> re-use go workflow

.github/workflows/linters.yml
=> re-use linters workflow

pkg/backend/backend_test.go, pkg/frontend/frontend_test.go, pkg/frontend/nvme_test.go, pkg/middleend/middleend_test.go, pkg/server/utils.go
=> Remove code duplication

pkg/backend/backend_test.go, pkg/frontend/frontend_test.go, pkg/frontend/nvme_test.go, pkg/middleend/middleend_test.go, pkg/server/utils.go
=> more code duplication fixes

pkg/backend/backend_test.go, pkg/frontend/nvme_test.go
=> Add missing listener

pkg/backend/backend_test.go, pkg/frontend/nvme_test.go, pkg/middleend/middleend_test.go, pkg/models/rpc.go, pkg/server/jsonrpc.go
=> models: new file for RPC headers/footers

pkg/models/rpc.go, pkg/server/jsonrpc.go
=> RPC: change id type to uint64

cmd/main.go, pkg/backend/backend.go, pkg/backend/backend_test.go, pkg/frontend/frontend.go, pkg/middleend/middleend.go, pkg/middleend/middleend_test.go
- Use NewServer() composition
- Align function signatures and impl
=> Use NewServer() composition

docker-compose.yml, pkg/frontend/frontend.go, pkg/frontend/frontend_test.go
=> ci: add TestFrontEnd for VirtioBlk

cmd/main.go, pkg/backend/backend.go, pkg/backend/backend_test.go, pkg/frontend/frontend.go, pkg/frontend/frontend_test.go, pkg/middleend/middleend.go, pkg/middleend/middleend_test.go
=> rename: NewServerWithJSONRPC() -> NewServer()

pkg/frontend/frontend.go
=> Add VirtioParameters

pkg/frontend/blk.go, pkg/frontend/blk_test.go
=> virtio: save controllers in global var

pkg/backend/aio.go, pkg/backend/backend.go, pkg/backend/null.go, pkg/backend/nvme.go
- backend: add VolumeParameters
- backend: use s.Volumes for Create()
- backend: use s.Volumes for Delete()
=> backend: add VolumeParameters

pkg/backend/aio.go, pkg/backend/aio_test.go, pkg/backend/null.go
=> tests: add TestBackEnd_CreateAioController

pkg/backend/null_test.go
=> tests: add TestBackEnd_CreateNullDebug

pkg/server/jsonrpc.go
=> unix: prepare for TCP

pkg/server/jsonrpc.go, pkg/server/utils.go
Help unify unix and tcp protocols
=> jsonrpc: make Call and communicate generic iface funcs

pkg/server/jsonrpc.go, pkg/server/jsonrpc_test.go
=> json: auto-discover unix/tcp transport

cmd/main.go, pkg/server/jsonrpc.go, pkg/server/jsonrpc_test.go, pkg/server/utils.go
=> rename UnixSocketJSONRPC to SpdkSocketJSONRPC

cmd/main.go, docker-compose.yml
=> main: allow SPDK to be TCP as well as UNIX

pkg/server/jsonrpc_test.go
=> spdk: test panic

cmd/main.go, docker-compose.yml, pkg/frontend/frontend.go, pkg/frontend/nvme.go, pkg/frontend/nvme_test.go
=> nvme: add port to tcpSubsystemListener

pkg/backend/aio.go, pkg/backend/aio_test.go, pkg/backend/null.go, pkg/backend/null_test.go
=> tests: add TestBackEnd AIO and NULL Get and Stats

pkg/backend/aio.go, pkg/backend/null.go, pkg/backend/nvme.go, pkg/frontend/blk.go, pkg/frontend/nvme.go
=> idempotency: delete should not fail if already deleted

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_test.go, pkg/frontend/blk.go, pkg/frontend/blk_test.go, pkg/frontend/nvme.go, pkg/frontend/nvme_test.go
=> tests: add key not found tests to delete

cmd/main.go, pkg/frontend/nvme.go, pkg/frontend/nvme_test.go
https://github.com/opiproject/opi-spdk-bridge/issues/279
=> Add ipv6 support for NVMe/TCP transport.

pkg/backend/aio.go, pkg/backend/aio_test.go
=> tests: implement TestBackEnd_UpdateAioController

pkg/backend/null.go, pkg/backend/null_test.go
=> tests: implement TestBackEnd_UpdateNullController

pkg/middleend/middleend.go, pkg/middleend/middleend_test.go
=> tests: implement TestMiddleEnd_UpdateEncryptedVolume

pkg/backend/aio.go, pkg/backend/aio_test.go, pkg/backend/null.go, pkg/backend/null_test.go, pkg/backend/nvme.go, pkg/backend/nvme_test.go, pkg/frontend/blk.go, pkg/frontend/blk_test.go, pkg/frontend/nvme.go, pkg/frontend/nvme_test.go, pkg/frontend/scsi.go, pkg/middleend/middleend.go, pkg/middleend/middleend_test.go
=> List: respect `page_size`

pkg/backend/nvme.go, pkg/models/spdk.go
=> backend: allow Hdgst and Ddgst

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_test.go, pkg/middleend/middleend_test.go, pkg/server/jsonrpc_test.go
=> tests: []struct -> map[string]struct

pkg/frontend/nvme_test.go
- tests: reflect.DeepEqual -> proto.Marshal
- tests: create if already exists
=> tests: create if already exists

pkg/frontend/nvme_test.go
=> test: error spdk_get_version

pkg/server/utils.go
=> tests: function rename

docker-compose.yml, scripts/tests.sh
=> Wait for client to finish for exit code

docker-compose.yml, pkg/frontend/scsi.go
=> Scsi: idempotent APIs

pkg/backend/aio.go, pkg/backend/null.go, pkg/backend/nvme.go, pkg/frontend/blk.go, pkg/frontend/scsi.go
=> create: use short name for spdk infra

pkg/frontend/scsi.go
=> scsi: fix return value of create object

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_test.go
=> linter: remove code dup

scripts/tests.sh
=> ci: remove spec id from test shell script

go.mod, go.sum, pkg/frontend/blk.go, pkg/frontend/frontend.go, pkg/frontend/nvme.go, pkg/frontend/nvme_test.go, pkg/kvm/kvm.go, pkg/kvm/nvme.go, pkg/kvm/nvme_test.go
Naming NVMe caused proto to force "nv_me" syntax which is weird
=> [storage] Rename NVMe -> Nvme

README.md, docker-compose.yml, scripts/tests.sh
Update tests and README after API change
=> NVMe -> Nvme and nv_me to nvme rename in tests and README.md.

go.mod, go.sum, pkg/backend/aio.go, pkg/backend/null.go, pkg/backend/nvme.go, pkg/frontend/blk.go, pkg/frontend/nvme.go, pkg/frontend/scsi.go, pkg/kvm/blk_test.go, pkg/middleend/encryption.go, pkg/server/utils.go, pkg/server/utils_test.go
=> Replace deepcopier with ProtoClone

docker-compose.yml
=> ci: bump spdk image to latest

pkg/backend/aio.go, pkg/backend/null.go
=> use path.Base as preparation for full names

pkg/backend/nvme.go, pkg/backend/nvme_test.go
=> tests: fix backend nvme tests

pkg/backend/aio.go, pkg/backend/aio_test.go, pkg/backend/null.go, pkg/backend/null_test.go, pkg/backend/nvme.go, pkg/backend/nvme_test.go
=> [backend] Get and Stats - handle unknown key

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_test.go, pkg/middleend/encryption_test.go
=> tests: fix expected error code print

pkg/frontend/blk.go, pkg/frontend/blk_test.go, pkg/frontend/scsi.go
=> [frontend] Get - handle unknown key

pkg/frontend/blk.go, pkg/frontend/blk_test.go, pkg/frontend/nvme.go, pkg/frontend/nvme_test.go, pkg/frontend/scsi.go
=> [frontend] Stats - handle unknown key

docker-compose.yml, scripts/tests.sh
=> ci: test with and without TLS

pkg/middleend/encryption.go, pkg/middleend/encryption_test.go, pkg/middleend/middleend.go
=> encryption: store objects in DB

go.mod, go.sum, pkg/middleend/qos.go, pkg/middleend/qos_test.go
Should land after https://github.com/opiproject/opi-api/pull/291
=> QoS volume LimitMin/LimitMax -> MinLimit/MaxLimit.

docker-compose.yml, pkg/middleend/encryption.go, pkg/middleend/encryption_test.go, pkg/middleend/qos.go, pkg/middleend/qos_test.go
Fixes #392
See https://google.aip.dev/122
=> [middleend] use full names

go.mod, go.sum, pkg/backend/aio.go, pkg/backend/aio_test.go, pkg/backend/null.go, pkg/backend/null_test.go, pkg/frontend/blk.go, pkg/frontend/blk_test.go, pkg/frontend/nvme.go, pkg/frontend/nvme_test.go, pkg/frontend/scsi.go
Adding `allow_missing` bool field
see https://google.aip.dev/134#create-or-update
=> Following Google AIP-134 - Standard methods: Update

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_test.go, pkg/middleend/encryption_test.go, pkg/middleend/middleend_test.go, pkg/middleend/qos_test.go
=> remove code dup

docker-compose.yml, go.mod, go.sum, pkg/backend/aio.go, pkg/backend/null.go, pkg/backend/nvme.go, pkg/backend/nvme_test.go, pkg/frontend/blk.go, pkg/frontend/nvme.go, pkg/frontend/scsi.go, pkg/middleend/encryption.go, pkg/middleend/qos.go
=> {resource}_id: call ValidateUserSettable

pkg/backend/aio.go, pkg/backend/null.go, pkg/frontend/blk.go, pkg/frontend/nvme.go, pkg/frontend/scsi.go
=> Update*: call fieldmask.Validate

pkg/middleend/qos.go
=> leftover server.ProtoClone

pkg/kvm/blk_test.go, pkg/kvm/nvme_test.go
=> tests: leftover server.ProtoClone

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_test.go, pkg/middleend/encryption_test.go, pkg/middleend/qos_test.go
=> tests: add UT for fieldmask.Validate

pkg/backend/aio.go, pkg/backend/null.go, pkg/backend/nvme.go, pkg/frontend/blk.go, pkg/frontend/nvme_controller.go, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_subsystem.go, pkg/frontend/scsi.go, pkg/middleend/encryption.go, pkg/middleend/qos.go
=> AIP-122: use resourcename.Validate

docker-compose.yml, go.mod, go.sum, pkg/backend/nvme_path.go
depends on
- https://github.com/opiproject/opi-api/pull/300
- https://github.com/opiproject/godpu/pull/223
=> [backend] NVMfPath: add list/get/stats rpcs

pkg/backend/nvme_path_test.go
starting with TestBackEnd_CreateNVMfPath
fixes #469
=> tests: add nvme_path_test.go

pkg/backend/nvme_path.go, pkg/backend/nvme_path_test.go
=> tests: add TestBackEnd_DeleteNVMfPath

pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path_test.go
=> tests: small nvme rename

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_path_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/middleend/encryption_test.go, pkg/middleend/qos_test.go
=> Update* prepare tests for AllowMissing

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/middleend/encryption_test.go
=> tests: add malformed name to Delete tests

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_path_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/middleend/encryption_test.go, pkg/middleend/qos.go, pkg/middleend/qos_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/460
=> test: add malformed name to Update tests

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/middleend/encryption_test.go, pkg/middleend/qos.go, pkg/middleend/qos_test.go
=> test: add malformed name to Stats tests

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path.go, pkg/backend/nvme_path_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/501
=> Uniformly check returned error on OK response in backend

pkg/kvm/blk_test.go, pkg/kvm/nvme_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/533
=> Uniformly check nil responses in frontend tests

pkg/middleend/encryption_test.go, pkg/middleend/qos_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/533
=> Uniformly check nil responses in middleend tests 

pkg/frontend/blk_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/533
=> Uniformly check nil responses in frontend tests 

pkg/backend/aio_test.go, pkg/backend/null_test.go, pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path_test.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/middleend/encryption_test.go, pkg/middleend/qos_test.go
No tests for Update and Stats calls since they do not have required fields yet
=> Test required fields

pkg/frontend/blk.go, pkg/frontend/blk_test.go, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_namespace_test.go, pkg/middleend/encryption.go, pkg/middleend/encryption_test.go
=> test(frontend): validate volume_name_ref resourcename

pkg/backend/aio_test.go, pkg/backend/backend_test.go, pkg/backend/null_test.go, pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path_test.go, pkg/frontend/blk_test.go, pkg/frontend/frontend_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/kvm/blk_test.go, pkg/kvm/kvm_test.go, pkg/kvm/nvme_test.go, pkg/middleend/encryption_test.go, pkg/middleend/middleend_test.go, pkg/middleend/qos_test.go, pkg/server/utils.go, pkg/server/utils_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/443
=> Use copies of global test objects

Dockerfile, README.md, cmd/main.go, docker-compose.yml
=> feat: add grpc gw http listener

README.md, docker-compose.yml, go.mod, go.sum, pkg/frontend/nvme_controller.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem.go, pkg/frontend/nvme_subsystem_test.go, pkg/kvm/nvme.go, pkg/kvm/nvme_test.go, pkg/server/utils_test.go, scripts/tests.sh
https://github.com/opiproject/opi-api/pull/333
Requires https://github.com/opiproject/godpu/pull/307
=> feat(frontend): nvme http annotation API change

cmd/main.go, pkg/frontend/frontend.go, pkg/frontend/frontend_test.go, pkg/frontend/nvme_controller.go, pkg/frontend/nvme_controller_test.go, pkg/kvm/nvme.go, pkg/kvm/nvme_test.go
see https://github.com/opiproject/opi-intel-bridge/pull/234#discussion_r1307536718
=> refact: SubsystemListener to NvmeTransport

cmd/main.go, pkg/backend/backend_test.go, pkg/frontend/frontend_test.go, pkg/kvm/blk_test.go, pkg/kvm/nvme_test.go, pkg/middleend/middleend_test.go, pkg/utils/codec.go
=> feat(store): use proto marshal instead of json

cmd/main.go, pkg/backend/aio.go, pkg/backend/aio_test.go, pkg/backend/backend_test.go, pkg/backend/null.go, pkg/backend/null_test.go, pkg/backend/nvme_controller.go, pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path.go, pkg/backend/nvme_path_test.go, pkg/frontend/blk.go, pkg/frontend/blk_test.go, pkg/frontend/frontend_test.go, pkg/frontend/nvme_controller.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem.go, pkg/frontend/nvme_subsystem_test.go, pkg/frontend/scsi.go, pkg/kvm/blk_test.go, pkg/kvm/kvm_test.go, pkg/kvm/nvme_test.go, pkg/middleend/encryption.go, pkg/middleend/encryption_test.go, pkg/middleend/middleend_test.go, pkg/middleend/qos.go, pkg/middleend/qos_test.go
=> refactor: fix go imports after rename

pkg/backend/aio_test.go, pkg/backend/backend_test.go, pkg/backend/null_test.go, pkg/backend/nvme_controller_test.go, pkg/backend/nvme_path_test.go, pkg/middleend/encryption_test.go, pkg/middleend/middleend_test.go
=> test: introduce withname struct

scripts/tests.sh
also add new curl test for inventory json http APIs
=> ci: add missing hostnqn to test script

pkg/frontend/blk.go, pkg/frontend/frontend.go, pkg/frontend/nvme_controller.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/transport.go, pkg/frontend/transport_test.go, pkg/kvm/nvme.go, pkg/kvm/nvme_test.go, pkg/kvm/transport.go, pkg/kvm/transport_test.go
=> refactor: move transport into new file

pkg/frontend/nvme_controller.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem.go, pkg/frontend/nvme_subsystem_test.go, pkg/kvm/nvme.go, pkg/kvm/nvme_test.go, pkg/kvm/transport.go, pkg/kvm/transport_test.go, pkg/utils/resource.go, pkg/utils/server.go
=> refactor: move resource funs into a new file

pkg/backend/backend.go, pkg/backend/nvme_path.go, pkg/backend/nvme_path_test.go, pkg/frontend/frontend.go, pkg/frontend/nvme_subsystem.go, pkg/frontend/nvme_subsystem_test.go, pkg/utils/psk.go, pkg/utils/psk_test.go
resolves https://github.com/opiproject/opi-spdk-bridge/issues/696
=> feat(frontend): write psk key to file

docker-compose.yml, pkg/frontend/blk_test.go, pkg/frontend/transport.go
fix https://github.com/opiproject/opi-spdk-bridge/issues/600
Requires https://github.com/opiproject/godpu/pull/334 to pass ci
=> fix(frontend): return error on non zero port/vf for vhost-user-blk

go.mod, go.sum, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_namespace_test.go
requires https://github.com/opiproject/opi-api/pull/383
=> refactor(frontend): adjust to changed states in nvme api

cmd/main.go, go.mod, go.sum
updates and fixes https://github.com/opiproject/opi-spdk-bridge/pull/747
=> fix(deps): update github.com/opiproject/opi-api digest to 7cfc284

pkg/utils/resource.go
fixes https://github.com/opiproject/opi-spdk-bridge/issues/742
=> refactor: use aip-go Join for resource names

pkg/middleend/encryption.go, pkg/middleend/middleend.go
Needed for https://github.com/opiproject/opi-intel-bridge/issues/85
=> feat: set non-default tweak mode to use

cmd/main.go, scripts/tests.sh
Only some basic checks are provided in the tests, since for the rest we need adjustments in the api http annotations and in the bridge code. The more comprehensive tests will be provided in the follow-up PRs
=> feat: enable http gateway for storage
